"""Report export to Excel, CSV and PDF.

Export only ever renders **already-validated** report data — either rows passed
back from a chat answer, or a stored assistant message the caller owns. There is
no "export this query" path, so export cannot become a way around the tool
surface or the permission scope.
"""

from __future__ import annotations

import csv
import datetime as dt
import io
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Sequence

from .response_formatter import COLUMN_FORMATS

logger = logging.getLogger("app.ai.export")

MAX_EXPORT_ROWS = 5000


@dataclass
class ReportMeta:
    """The provenance block every exported report carries.

    A spreadsheet that leaves the system without its filters and period attached
    is a number without a question — six months later nobody can tell what it
    measured. This block travels with all three formats.
    """

    company_name: str = "Company"
    report_name: str = "Report"
    date_range: str | None = None
    filters: dict[str, Any] = field(default_factory=dict)
    generated_by: str | None = None
    generated_at: dt.datetime | None = None
    currency: str = "BDT"
    note: str | None = None

    def lines(self) -> list[tuple[str, str]]:
        """The metadata as ``(label, value)`` pairs, in display order."""
        generated = self.generated_at or dt.datetime.now()
        rows: list[tuple[str, str]] = [
            ("Company", self.company_name),
            ("Report", self.report_name),
        ]
        if self.date_range:
            rows.append(("Date Range", self.date_range))
        rows.append(("Filters", self.filter_text()))
        if self.generated_by:
            rows.append(("Generated By", self.generated_by))
        rows.append(("Generated Date", generated.strftime("%d %b %Y %H:%M")))
        rows.append(("Currency", self.currency))
        if self.note:
            rows.append(("Note", self.note))
        return rows

    def filter_text(self) -> str:
        applied = {k: v for k, v in (self.filters or {}).items() if v}
        if not applied:
            return "None (all data within your access)"
        return "; ".join(
            f"{key.replace('_codes', '').replace('_code', '').replace('_', ' ').title()}"
            f": {', '.join(map(str, value)) if isinstance(value, (list, tuple)) else value}"
            for key, value in applied.items()
        )


def _columns(rows: Sequence[dict[str, Any]]) -> list[str]:
    columns: list[str] = []
    for row in rows:
        for key in row:
            if key not in columns:
                columns.append(key)
    return columns


def _heading(column: str) -> str:
    return COLUMN_FORMATS.get(column, (column.replace("_", " ").title(),))[0]


def _cell(value: Any) -> Any:
    if isinstance(value, (dict, list)):
        return str(value)
    return value


def to_csv(rows: Sequence[dict[str, Any]], meta: ReportMeta | None = None) -> bytes:
    """UTF-8 with a BOM so Excel opens Bangla text correctly.

    The metadata block is written as leading ``# key,value`` lines, which most
    spreadsheet tools show as ordinary rows and scripts can skip.
    """
    rows = list(rows)[:MAX_EXPORT_ROWS]
    buffer = io.StringIO()
    writer = csv.writer(buffer)

    if meta is not None:
        for label, value in meta.lines():
            writer.writerow([f"# {label}", value])
        writer.writerow([])

    if rows:
        columns = _columns(rows)
        writer.writerow([_heading(c) for c in columns])
        for row in rows:
            writer.writerow([_cell(row.get(c)) for c in columns])
    else:
        writer.writerow(["No data found for the selected period and filters."])
    return ("﻿" + buffer.getvalue()).encode("utf-8")


#: Column name fragments -> Excel number format.
_NUMBER_FORMATS: tuple[tuple[tuple[str, ...], str], ...] = (
    (("_percent", "_pct", "achievement", "margin", "growth", "share"), "0.0\\%"),
    (("sales", "amount", "price", "profit", "cost", "discount", "target", "gap"),
     "#,##0.00"),
    (("quantity", "qty", "stock", "count", "days"), "#,##0.00"),
)


def _number_format(column: str) -> str | None:
    lowered = column.lower()
    for fragments, fmt in _NUMBER_FORMATS:
        if any(fragment in lowered for fragment in fragments):
            return fmt
    return None


def to_xlsx(rows: Sequence[dict[str, Any]], title: str = "Report",
            meta: ReportMeta | None = None) -> bytes:
    """An Excel workbook with a metadata block, frozen header and auto-filter."""
    from openpyxl import Workbook
    from openpyxl.styles import Alignment, Font, PatternFill
    from openpyxl.utils import get_column_letter

    rows = list(rows)[:MAX_EXPORT_ROWS]
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = (title or "Report")[:31]

    label_font = Font(bold=True)
    header_row = 1

    if meta is not None:
        sheet["A1"] = meta.report_name
        sheet["A1"].font = Font(bold=True, size=14)
        for offset, (label, value) in enumerate(meta.lines(), start=2):
            sheet.cell(row=offset, column=1, value=label).font = label_font
            sheet.cell(row=offset, column=2, value=value)
        header_row = len(meta.lines()) + 3      # one blank row before the data

    if rows:
        columns = _columns(rows)
        for index, column in enumerate(columns, start=1):
            sheet.cell(row=header_row, column=index, value=_heading(column))
        for row_offset, row in enumerate(rows, start=header_row + 1):
            for index, column in enumerate(columns, start=1):
                cell = sheet.cell(row=row_offset, column=index,
                                  value=_cell(row.get(column)))
                if isinstance(cell.value, (int, float)):
                    fmt = _number_format(column)
                    if fmt:
                        cell.number_format = fmt
                elif isinstance(cell.value, (dt.date, dt.datetime)):
                    cell.number_format = "dd mmm yyyy"

        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill("solid", fgColor="1F4E79")
        for index in range(1, len(columns) + 1):
            cell = sheet.cell(row=header_row, column=index)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(vertical="center", wrap_text=True)
            longest = max(
                (len(str(sheet.cell(row=r, column=index).value or ""))
                 for r in range(header_row, sheet.max_row + 1)),
                default=12,
            )
            sheet.column_dimensions[get_column_letter(index)].width = min(
                max(12, longest + 2), 40
            )
        last_column = get_column_letter(len(columns))
        sheet.auto_filter.ref = f"A{header_row}:{last_column}{sheet.max_row}"
        sheet.freeze_panes = f"A{header_row + 1}"
    else:
        sheet.cell(row=header_row, column=1,
                   value="No data found for the selected period and filters.")

    buffer = io.BytesIO()
    workbook.save(buffer)
    return buffer.getvalue()


def to_pdf(rows: Sequence[dict[str, Any]], title: str = "Report",
           subtitle: str | None = None, meta: ReportMeta | None = None,
           kpis: Sequence[tuple[str, str]] | None = None) -> bytes:
    """A landscape PDF report: header block, KPI summary, then the table.

    Bangla glyphs need a font with Bengali coverage. If ``PDF_BANGLA_FONT``
    points at a TTF it is registered and used; otherwise non-Latin text is
    replaced with ``?`` rather than rendered as blank boxes, and the report says
    so instead of silently dropping characters.
    """
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        Paragraph,
        SimpleDocTemplate,
        Spacer,
        Table,
        TableStyle,
    )

    rows = list(rows)[:MAX_EXPORT_ROWS]
    buffer = io.BytesIO()
    document = SimpleDocTemplate(
        buffer, pagesize=landscape(A4),
        leftMargin=12 * mm, rightMargin=12 * mm,
        topMargin=12 * mm, bottomMargin=12 * mm,
        title=title,
    )
    styles = getSampleStyleSheet()
    body_font = _register_unicode_font()
    text = (lambda value: str(value)) if body_font else _latin

    story: list[Any] = []
    if meta is not None:
        story.append(Paragraph(text(meta.company_name), styles["Heading2"]))
        story.append(Paragraph(text(meta.report_name), styles["Title"]))
        info = [f"<b>{text(label)}:</b> {text(value)}" for label, value in meta.lines()
                if label not in ("Company", "Report")]
        for line in info:
            story.append(Paragraph(line, styles["Normal"]))
    else:
        story.append(Paragraph(text(title), styles["Title"]))
    if subtitle:
        story.append(Paragraph(text(subtitle), styles["Normal"]))
    story.append(Spacer(1, 5 * mm))

    if kpis:
        story.append(Paragraph("<b>Summary</b>", styles["Heading3"]))
        kpi_table = Table([[text(label), text(value)] for label, value in kpis],
                          colWidths=[60 * mm, 40 * mm])
        kpi_table.setStyle(TableStyle([
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#D0D0D0")),
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#F2F6FA")),
            ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ]))
        story.append(kpi_table)
        story.append(Spacer(1, 5 * mm))

    if not rows:
        story.append(Paragraph("No data found for the selected period and filters.",
                               styles["Normal"]))
    else:
        columns = _columns(rows)[:10]     # a wider table stops being readable
        table_data = [[text(_heading(c)) for c in columns]]
        for row in rows:
            table_data.append([text(_cell(row.get(c)) or "") for c in columns])
        table = Table(table_data, repeatRows=1)
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F4E79")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), body_font or "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), body_font or "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#B0B0B0")),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1),
             [colors.white, colors.HexColor("#F2F6FA")]),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(table)

    document.build(story)
    return buffer.getvalue()


def _latin(text: Any) -> str:
    """Replace characters the built-in PDF fonts cannot draw."""
    return "".join(ch if ord(ch) < 0x0250 else "?" for ch in str(text))


_FONT_NAME = "BanglaBody"
_font_registered: bool | None = None


def _register_unicode_font() -> str | None:
    """Register the configured Bengali TTF, once. Returns its name or ``None``.

    Set ``PDF_BANGLA_FONT`` to a TTF with Bengali coverage (for example
    ``NotoSansBengali-Regular.ttf``) to get real Bangla in PDF exports.
    """
    global _font_registered
    path = os.getenv("PDF_BANGLA_FONT")
    if not path:
        return None
    if _font_registered is not None:
        return _FONT_NAME if _font_registered else None

    try:
        from reportlab.pdfbase import pdfmetrics
        from reportlab.pdfbase.ttfonts import TTFont

        pdfmetrics.registerFont(TTFont(_FONT_NAME, path))
        _font_registered = True
    except Exception:  # noqa: BLE001 - a missing font degrades, never breaks
        logger.warning("could not register PDF_BANGLA_FONT %r; Bangla will be "
                       "transliterated in PDF exports", path)
        _font_registered = False
    return _FONT_NAME if _font_registered else None


def supports_bangla_pdf() -> bool:
    """Whether PDF export can render Bangla, for the UI to warn about."""
    return _register_unicode_font() is not None


CONTENT_TYPES = {
    "csv": "text/csv; charset=utf-8",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "pdf": "application/pdf",
}


def render(export_format: str, rows: Sequence[dict[str, Any]], title: str = "Report",
           subtitle: str | None = None, meta: ReportMeta | None = None,
           kpis: Sequence[tuple[str, str]] | None = None) -> tuple[bytes, str]:
    """``(payload, content_type)`` for the requested format."""
    if export_format == "csv":
        return to_csv(rows, meta), CONTENT_TYPES["csv"]
    if export_format == "xlsx":
        return to_xlsx(rows, title, meta), CONTENT_TYPES["xlsx"]
    if export_format == "pdf":
        return to_pdf(rows, title, subtitle, meta, kpis), CONTENT_TYPES["pdf"]
    raise ValueError(f"Unsupported export format: {export_format}")


__all__ = ["render", "to_csv", "to_xlsx", "to_pdf", "ReportMeta", "CONTENT_TYPES",
           "MAX_EXPORT_ROWS", "supports_bangla_pdf"]
