"""Phase 2: transaction warehouse layer.

Adds, on top of the Phase 1 master dimensions (which are left untouched):

* ``dim_date`` — calendar plus a configurable financial-year calendar
* ``dim_customer`` / ``dim_sales_force`` / ``dim_warehouse`` — future-ready
  dimensions, created empty and registered as PENDING_SOURCE_DATA
* ``etl_import_batches``, ``etl_rejected_records``, ``etl_master_source_status``
* ``stg_*`` staging tables preserving the source shape as text
* ``fact_sales``, ``fact_collection``, ``fact_outstanding``, ``fact_stock``,
  ``fact_target``

Every fact carries a UNIQUE ``business_key`` (the configurable de-duplication
key from ``etl.datasets``) so a repeated import updates rather than duplicates.

Revision ID: 0002_warehouse_layer
Revises: 0001_master_data_dimensions
Create Date: 2026-08-10
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002_warehouse_layer'
down_revision: Union[str, None] = '0001_master_data_dimensions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_customer',
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('customer_code', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=True),
    sa.Column('customer_type', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_index('ix_dim_customer_customer_code', 'dim_customer', ['customer_code'], unique=False)
    op.create_index('ix_dim_customer_status', 'dim_customer', ['status'], unique=False)
    op.create_table('dim_date',
    sa.Column('date_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day', sa.SmallInteger(), nullable=False),
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('month_name', sa.String(length=16), nullable=False),
    sa.Column('month_number', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False),
    sa.Column('quarter_name', sa.String(length=8), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('week', sa.SmallInteger(), nullable=False),
    sa.Column('week_name', sa.String(length=16), nullable=False),
    sa.Column('financial_year', sa.String(length=16), nullable=False),
    sa.Column('financial_month', sa.SmallInteger(), nullable=False),
    sa.Column('financial_quarter', sa.SmallInteger(), nullable=False),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.Column('is_quarter_end', sa.Boolean(), nullable=False),
    sa.Column('is_year_end', sa.Boolean(), nullable=False),
    sa.Column('is_financial_year_end', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date_id'),
    sa.UniqueConstraint('full_date')
    )
    op.create_index('ix_dim_date_financial_year', 'dim_date', ['financial_year'], unique=False)
    op.create_index('ix_dim_date_full_date', 'dim_date', ['full_date'], unique=False)
    op.create_index('ix_dim_date_year_month', 'dim_date', ['year', 'month'], unique=False)
    op.create_table('dim_sales_force',
    sa.Column('sales_force_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('sales_force_code', sa.String(length=64), nullable=False),
    sa.Column('sales_force_name', sa.Text(), nullable=True),
    sa.Column('designation', sa.Text(), nullable=True),
    sa.Column('employee_id', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('sales_force_id'),
    sa.UniqueConstraint('sales_force_code')
    )
    op.create_index('ix_dim_sales_force_sales_force_code', 'dim_sales_force', ['sales_force_code'], unique=False)
    op.create_index('ix_dim_sales_force_territory_code', 'dim_sales_force', ['territory_code'], unique=False)
    op.create_table('dim_warehouse',
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('warehouse_code', sa.String(length=64), nullable=False),
    sa.Column('warehouse_name', sa.Text(), nullable=True),
    sa.Column('warehouse_type', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.create_index('ix_dim_warehouse_warehouse_code', 'dim_warehouse', ['warehouse_code'], unique=False)
    op.create_table('etl_import_batches',
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_uuid', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('load_mode', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('batch_uuid')
    )
    op.create_index('ix_etl_import_batches_data_type', 'etl_import_batches', ['data_type'], unique=False)
    op.create_index('ix_etl_import_batches_source_system', 'etl_import_batches', ['source_system'], unique=False)
    op.create_index('ix_etl_import_batches_started_at', 'etl_import_batches', ['started_at'], unique=False)
    op.create_index('ix_etl_import_batches_status', 'etl_import_batches', ['status'], unique=False)
    op.create_table('etl_master_source_status',
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('table_name')
    )
    op.create_table('etl_rejected_records',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_category', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etl_rejected_records_batch_id', 'etl_rejected_records', ['batch_id'], unique=False)
    op.create_index('ix_etl_rejected_records_data_type', 'etl_rejected_records', ['data_type'], unique=False)
    op.create_index('ix_etl_rejected_records_error_code', 'etl_rejected_records', ['error_code'], unique=False)
    op.create_table('stg_collection',
    sa.Column('transaction_date', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.String(length=128), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('collection_amount', sa.String(length=64), nullable=True),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('staging_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('bu_code', sa.String(length=64), nullable=True),
    sa.Column('sales_line_code', sa.String(length=64), nullable=True),
    sa.Column('zone_code', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=64), nullable=True),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('sub_territory_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_stg_collection_batch', 'stg_collection', ['import_batch_id', 'validation_status'], unique=False)
    op.create_table('stg_outstanding',
    sa.Column('as_on_date', sa.String(length=64), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.String(length=64), nullable=True),
    sa.Column('due_date', sa.String(length=64), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('invoice_amount', sa.String(length=64), nullable=True),
    sa.Column('paid_amount', sa.String(length=64), nullable=True),
    sa.Column('outstanding_amount', sa.String(length=64), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('staging_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('bu_code', sa.String(length=64), nullable=True),
    sa.Column('sales_line_code', sa.String(length=64), nullable=True),
    sa.Column('zone_code', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=64), nullable=True),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('sub_territory_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_stg_outstanding_batch', 'stg_outstanding', ['import_batch_id', 'validation_status'], unique=False)
    op.create_table('stg_sales',
    sa.Column('transaction_date', sa.String(length=64), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('gross_sales', sa.String(length=64), nullable=True),
    sa.Column('discount', sa.String(length=64), nullable=True),
    sa.Column('net_sales', sa.String(length=64), nullable=True),
    sa.Column('cost', sa.String(length=64), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('staging_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('bu_code', sa.String(length=64), nullable=True),
    sa.Column('sales_line_code', sa.String(length=64), nullable=True),
    sa.Column('zone_code', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=64), nullable=True),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('sub_territory_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_stg_sales_batch', 'stg_sales', ['import_batch_id', 'validation_status'], unique=False)
    op.create_table('stg_stock',
    sa.Column('stock_date', sa.String(length=64), nullable=True),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=True),
    sa.Column('opening_stock', sa.String(length=64), nullable=True),
    sa.Column('purchase_qty', sa.String(length=64), nullable=True),
    sa.Column('sales_qty', sa.String(length=64), nullable=True),
    sa.Column('transfer_in', sa.String(length=64), nullable=True),
    sa.Column('transfer_out', sa.String(length=64), nullable=True),
    sa.Column('closing_stock', sa.String(length=64), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('staging_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('bu_code', sa.String(length=64), nullable=True),
    sa.Column('sales_line_code', sa.String(length=64), nullable=True),
    sa.Column('zone_code', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=64), nullable=True),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('sub_territory_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_stg_stock_batch', 'stg_stock', ['import_batch_id', 'validation_status'], unique=False)
    op.create_table('stg_target',
    sa.Column('target_date', sa.String(length=64), nullable=True),
    sa.Column('target_period', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('sku_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('target_amount', sa.String(length=64), nullable=True),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('staging_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=True),
    sa.Column('raw_data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('company_code', sa.String(length=64), nullable=True),
    sa.Column('bu_code', sa.String(length=64), nullable=True),
    sa.Column('sales_line_code', sa.String(length=64), nullable=True),
    sa.Column('zone_code', sa.String(length=64), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('area_code', sa.String(length=64), nullable=True),
    sa.Column('unit_code', sa.String(length=64), nullable=True),
    sa.Column('territory_code', sa.String(length=64), nullable=True),
    sa.Column('sub_territory_code', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staging_id')
    )
    op.create_index('ix_stg_target_batch', 'stg_target', ['import_batch_id', 'validation_status'], unique=False)
    op.create_table('fact_stock',
    sa.Column('stock_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.Column('opening_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('purchase_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('sales_qty', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transfer_in', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('transfer_out', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closing_stock', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closing_stock_from_source', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('business_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('business_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dim_area.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['dim_business_unit.business_unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_line_id'], ['dim_sales_line.sales_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['dim_unit.unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.warehouse_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['dim_zone.zone_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('business_key', name='uq_fact_stock_business_key')
    )
    op.create_index('ix_fact_stock_batch', 'fact_stock', ['import_batch_id'], unique=False)
    op.create_index('ix_fact_stock_date_id', 'fact_stock', ['date_id'], unique=False)
    op.create_index('ix_fact_stock_date_product', 'fact_stock', ['date_id', 'product_id'], unique=False)
    op.create_index('ix_fact_stock_product_id', 'fact_stock', ['product_id'], unique=False)
    op.create_index('ix_fact_stock_source_system', 'fact_stock', ['source_system'], unique=False)
    op.create_index('ix_fact_stock_warehouse_id', 'fact_stock', ['warehouse_id'], unique=False)
    op.create_table('fact_collection',
    sa.Column('collection_pk', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_force_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('collection_id', sa.String(length=128), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('collection_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=True),
    sa.Column('territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sub_territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('business_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('business_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dim_area.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['dim_business_unit.business_unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_force_id'], ['dim_sales_force.sales_force_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_line_id'], ['dim_sales_line.sales_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_territory_id'], ['dim_sub_territory.sub_territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['dim_territory.territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['dim_unit.unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['dim_zone.zone_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('collection_pk'),
    sa.UniqueConstraint('business_key', name='uq_fact_collection_business_key')
    )
    op.create_index('ix_fact_collection_batch', 'fact_collection', ['import_batch_id'], unique=False)
    op.create_index('ix_fact_collection_date_id', 'fact_collection', ['date_id'], unique=False)
    op.create_index('ix_fact_collection_invoice_no', 'fact_collection', ['invoice_no'], unique=False)
    op.create_index('ix_fact_collection_region_id', 'fact_collection', ['region_id'], unique=False)
    op.create_index('ix_fact_collection_source_system', 'fact_collection', ['source_system'], unique=False)
    op.create_table('fact_outstanding',
    sa.Column('outstanding_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_force_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('days_overdue', sa.Integer(), nullable=False),
    sa.Column('aging_bucket', sa.String(length=16), nullable=False),
    sa.Column('territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sub_territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('business_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('business_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dim_area.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['dim_business_unit.business_unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_force_id'], ['dim_sales_force.sales_force_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_line_id'], ['dim_sales_line.sales_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_territory_id'], ['dim_sub_territory.sub_territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['dim_territory.territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['dim_unit.unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['dim_zone.zone_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('outstanding_id'),
    sa.UniqueConstraint('business_key', name='uq_fact_outstanding_business_key')
    )
    op.create_index('ix_fact_outstanding_aging_bucket', 'fact_outstanding', ['aging_bucket'], unique=False)
    op.create_index('ix_fact_outstanding_batch', 'fact_outstanding', ['import_batch_id'], unique=False)
    op.create_index('ix_fact_outstanding_date_id', 'fact_outstanding', ['date_id'], unique=False)
    op.create_index('ix_fact_outstanding_region_id', 'fact_outstanding', ['region_id'], unique=False)
    op.create_index('ix_fact_outstanding_source_system', 'fact_outstanding', ['source_system'], unique=False)
    op.create_table('fact_sales',
    sa.Column('sales_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_force_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('warehouse_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('customer_code', sa.String(length=64), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('warehouse_code', sa.String(length=64), nullable=True),
    sa.Column('invoice_no', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_sales', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('discount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_sales', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sub_territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('business_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('business_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dim_area.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['dim_business_unit.business_unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_force_id'], ['dim_sales_force.sales_force_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_line_id'], ['dim_sales_line.sales_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_territory_id'], ['dim_sub_territory.sub_territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['dim_territory.territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['dim_unit.unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.warehouse_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['dim_zone.zone_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('sales_id'),
    sa.UniqueConstraint('business_key', name='uq_fact_sales_business_key')
    )
    op.create_index('ix_fact_sales_batch', 'fact_sales', ['import_batch_id'], unique=False)
    op.create_index('ix_fact_sales_date_id', 'fact_sales', ['date_id'], unique=False)
    op.create_index('ix_fact_sales_date_region', 'fact_sales', ['date_id', 'region_id'], unique=False)
    op.create_index('ix_fact_sales_invoice_no', 'fact_sales', ['invoice_no'], unique=False)
    op.create_index('ix_fact_sales_product_id', 'fact_sales', ['product_id'], unique=False)
    op.create_index('ix_fact_sales_region_id', 'fact_sales', ['region_id'], unique=False)
    op.create_index('ix_fact_sales_source_system', 'fact_sales', ['source_system'], unique=False)
    op.create_index('ix_fact_sales_territory_id', 'fact_sales', ['territory_id'], unique=False)
    op.create_table('fact_target',
    sa.Column('target_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_force_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_force_code', sa.String(length=64), nullable=True),
    sa.Column('target_period', sa.String(length=32), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sub_territory_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('company_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('business_unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('sales_line_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('zone_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('region_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('unit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('source_system', sa.String(length=32), nullable=False),
    sa.Column('source_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('business_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('import_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['dim_area.area_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['business_unit_id'], ['dim_business_unit.business_unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['company_id'], ['dim_company.company_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['date_id'], ['dim_date.date_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['etl_import_batches.batch_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_force_id'], ['dim_sales_force.sales_force_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_line_id'], ['dim_sales_line.sales_line_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sub_territory_id'], ['dim_sub_territory.sub_territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['territory_id'], ['dim_territory.territory_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['dim_unit.unit_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone_id'], ['dim_zone.zone_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('target_id'),
    sa.UniqueConstraint('business_key', name='uq_fact_target_business_key')
    )
    op.create_index('ix_fact_target_batch', 'fact_target', ['import_batch_id'], unique=False)
    op.create_index('ix_fact_target_date_id', 'fact_target', ['date_id'], unique=False)
    op.create_index('ix_fact_target_period', 'fact_target', ['target_period'], unique=False)
    op.create_index('ix_fact_target_product_id', 'fact_target', ['product_id'], unique=False)
    op.create_index('ix_fact_target_region_id', 'fact_target', ['region_id'], unique=False)
    op.create_index('ix_fact_target_source_system', 'fact_target', ['source_system'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fact_target_source_system', table_name='fact_target')
    op.drop_index('ix_fact_target_region_id', table_name='fact_target')
    op.drop_index('ix_fact_target_product_id', table_name='fact_target')
    op.drop_index('ix_fact_target_period', table_name='fact_target')
    op.drop_index('ix_fact_target_date_id', table_name='fact_target')
    op.drop_index('ix_fact_target_batch', table_name='fact_target')
    op.drop_table('fact_target')
    op.drop_index('ix_fact_sales_territory_id', table_name='fact_sales')
    op.drop_index('ix_fact_sales_source_system', table_name='fact_sales')
    op.drop_index('ix_fact_sales_region_id', table_name='fact_sales')
    op.drop_index('ix_fact_sales_product_id', table_name='fact_sales')
    op.drop_index('ix_fact_sales_invoice_no', table_name='fact_sales')
    op.drop_index('ix_fact_sales_date_region', table_name='fact_sales')
    op.drop_index('ix_fact_sales_date_id', table_name='fact_sales')
    op.drop_index('ix_fact_sales_batch', table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index('ix_fact_outstanding_source_system', table_name='fact_outstanding')
    op.drop_index('ix_fact_outstanding_region_id', table_name='fact_outstanding')
    op.drop_index('ix_fact_outstanding_date_id', table_name='fact_outstanding')
    op.drop_index('ix_fact_outstanding_batch', table_name='fact_outstanding')
    op.drop_index('ix_fact_outstanding_aging_bucket', table_name='fact_outstanding')
    op.drop_table('fact_outstanding')
    op.drop_index('ix_fact_collection_source_system', table_name='fact_collection')
    op.drop_index('ix_fact_collection_region_id', table_name='fact_collection')
    op.drop_index('ix_fact_collection_invoice_no', table_name='fact_collection')
    op.drop_index('ix_fact_collection_date_id', table_name='fact_collection')
    op.drop_index('ix_fact_collection_batch', table_name='fact_collection')
    op.drop_table('fact_collection')
    # The old stock tables are conditional: revision 0016 replaced the whole
    # stock module and dropped them, so a downgrade reaching this revision on
    # any current database will not find them. Their absence is expected.
    existing = set(sa.inspect(op.get_bind()).get_table_names())
    if 'fact_stock' in existing:
        op.drop_index('ix_fact_stock_warehouse_id', table_name='fact_stock')
        op.drop_index('ix_fact_stock_source_system', table_name='fact_stock')
        op.drop_index('ix_fact_stock_product_id', table_name='fact_stock')
        op.drop_index('ix_fact_stock_date_product', table_name='fact_stock')
        op.drop_index('ix_fact_stock_date_id', table_name='fact_stock')
        op.drop_index('ix_fact_stock_batch', table_name='fact_stock')
        op.drop_table('fact_stock')
    op.drop_index('ix_stg_target_batch', table_name='stg_target')
    op.drop_table('stg_target')
    if 'stg_stock' in existing:
        op.drop_index('ix_stg_stock_batch', table_name='stg_stock')
        op.drop_table('stg_stock')
    op.drop_index('ix_stg_sales_batch', table_name='stg_sales')
    op.drop_table('stg_sales')
    op.drop_index('ix_stg_outstanding_batch', table_name='stg_outstanding')
    op.drop_table('stg_outstanding')
    op.drop_index('ix_stg_collection_batch', table_name='stg_collection')
    op.drop_table('stg_collection')
    op.drop_index('ix_etl_rejected_records_error_code', table_name='etl_rejected_records')
    op.drop_index('ix_etl_rejected_records_data_type', table_name='etl_rejected_records')
    op.drop_index('ix_etl_rejected_records_batch_id', table_name='etl_rejected_records')
    op.drop_table('etl_rejected_records')
    op.drop_table('etl_master_source_status')
    op.drop_index('ix_etl_import_batches_status', table_name='etl_import_batches')
    op.drop_index('ix_etl_import_batches_started_at', table_name='etl_import_batches')
    op.drop_index('ix_etl_import_batches_source_system', table_name='etl_import_batches')
    op.drop_index('ix_etl_import_batches_data_type', table_name='etl_import_batches')
    op.drop_table('etl_import_batches')
    op.drop_index('ix_dim_warehouse_warehouse_code', table_name='dim_warehouse')
    op.drop_table('dim_warehouse')
    op.drop_index('ix_dim_sales_force_territory_code', table_name='dim_sales_force')
    op.drop_index('ix_dim_sales_force_sales_force_code', table_name='dim_sales_force')
    op.drop_table('dim_sales_force')
    op.drop_index('ix_dim_date_year_month', table_name='dim_date')
    op.drop_index('ix_dim_date_full_date', table_name='dim_date')
    op.drop_index('ix_dim_date_financial_year', table_name='dim_date')
    op.drop_table('dim_date')
    op.drop_index('ix_dim_customer_status', table_name='dim_customer')
    op.drop_index('ix_dim_customer_customer_code', table_name='dim_customer')
    op.drop_table('dim_customer')
    # ### end Alembic commands ###
