"""Phase 4: web platform — auth, audit logs and notifications.

Revision ID: 0005_platform
Revises: 0004_ai_layer
Create Date: 2026-08-10 20:42:20.677533
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0005_platform'
down_revision: Union[str, None] = '0004_ai_layer'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    # batch_alter_table so SQLite (which cannot ALTER TABLE ADD CONSTRAINT)
    # recreates the table, while PostgreSQL applies the changes directly.
    # Constraints are named explicitly so downgrade can drop them.
    with op.batch_alter_table('app_user') as batch:
        batch.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        batch.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch.add_column(sa.Column('phone_number', sa.String(length=32), nullable=True))
        batch.add_column(sa.Column('last_login_at', sa.DateTime(timezone=True),
                                   nullable=True))
        # server_default is required: existing rows need a value for a NOT NULL
        # column added after the fact.
        batch.add_column(sa.Column('theme', sa.String(length=16), nullable=False,
                                   server_default='system'))
        batch.create_unique_constraint('uq_app_user_email', ['email'])
        batch.create_unique_constraint('uq_app_user_phone_number', ['phone_number'])

    op.create_index('ix_app_user_email', 'app_user', ['email'], unique=False)
    op.create_index('ix_app_user_phone_number', 'app_user', ['phone_number'],
                    unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_app_user_phone_number', table_name='app_user')
    op.drop_index('ix_app_user_email', table_name='app_user')
    with op.batch_alter_table('app_user') as batch:
        batch.drop_constraint('uq_app_user_phone_number', type_='unique')
        batch.drop_constraint('uq_app_user_email', type_='unique')
        batch.drop_column('theme')
        batch.drop_column('last_login_at')
        batch.drop_column('phone_number')
        batch.drop_column('password_hash')
        batch.drop_column('email')
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
