/**
 * Everything the map is configured with, in one place.
 *
 * The engine is MapLibre GL JS and the basemap is OpenFreeMap. Neither needs an
 * API key, which is the reason for the pair: the previous implementation carried
 * a Google Maps browser key that had to be served to the page and restricted by
 * referrer, and a hand-written Web Mercator canvas renderer as the fallback for
 * deployments without one. One engine that works everywhere replaces both.
 *
 * Administrative geometry is served from `public/geo/`, generated by
 * `scripts/build_map_geojson.py` from the published HDX release. It is a static
 * asset, not an endpoint: boundaries change only when somebody imports a new
 * release, so a request per page load would be work with no answer that differs.
 * Business data still comes from the API, because that is the only thing that
 * knows the caller's permissions.
 */

import type { AreaStyle } from '../../types/api';

/**
 * OpenFreeMap style URLs, one per theme.
 *
 * Both are deliberately muted designs rather than the colourful `liberty` or
 * `bright` styles the same host offers: a business map is read for the data
 * drawn on top of it, and a vivid basemap competes with the very markers and
 * boundaries it exists to support.
 *
 * The backend may override these through `/api/map/config`, so a deployment
 * behind a firewall can point at its own tile server without a rebuild.
 */
export const BASEMAP_STYLES = {
  light: 'https://tiles.openfreemap.org/styles/positron',
  dark: 'https://tiles.openfreemap.org/styles/dark',
} as const;

/** Where `scripts/build_map_geojson.py` writes, relative to the site root. */
const GEO = '/geo';

export const GEO_FILES = {
  country: `${GEO}/bgd_admin0.geojson`,
  division: `${GEO}/bgd_admin1.geojson`,
  district: `${GEO}/bgd_admin2.geojson`,
  upazila: `${GEO}/bgd_admin3.geojson`,
  capitals: `${GEO}/bgd_admincapitals.geojson`,
  points: `${GEO}/bgd_adminpoints.geojson`,
  lines: `${GEO}/bgd_adminlines.geojson`,
  mask: `${GEO}/bgd_mask.geojson`,
} as const;

export type GeoFileKey = keyof typeof GEO_FILES;

/**
 * The four administrative levels, outermost first.
 *
 * `code` is the P-code the published file carries (`BD`, `BD10`, `BD1004`,
 * `BD20030004`) and the same value `dim_country`/`dim_division`/`dim_district`/
 * `dim_upazila` store, which is what lets a locally-drawn polygon be joined to a
 * server-computed metric without a lookup table between them.
 */
export interface BoundaryLevel {
  key: 'country' | 'division' | 'district' | 'upazila';
  file: GeoFileKey;
  labelKey: string;
  /** Below this zoom the level is not drawn: 507 upazilas at zoom 6 is mush. */
  minZoom: number;
  /** On by default? Only the country outline and upazilas are, per level 12. */
  defaultOn: boolean;
}

export const BOUNDARY_LEVELS: readonly BoundaryLevel[] = [
  { key: 'country', file: 'country', labelKey: 'map.levelCountry', minZoom: 0, defaultOn: true },
  { key: 'division', file: 'division', labelKey: 'map.levelDivision', minZoom: 0, defaultOn: true },
  { key: 'district', file: 'district', labelKey: 'map.levelDistrict', minZoom: 6, defaultOn: false },
  { key: 'upazila', file: 'upazila', labelKey: 'map.levelUpazila', minZoom: 7, defaultOn: false },
] as const;

export type BoundaryLevelKey = BoundaryLevel['key'];

/**
 * Appearance if the API has not answered yet.
 *
 * The authority is `map_area_styles` in the database, served through
 * `/api/map/config` — a colour decided in the browser would be a second source
 * of truth, and the marker designer would no longer describe what is drawn.
 * These values are the same ones migrations `0010` and `0017` seed, so the first
 * paint matches the configured one instead of flashing a different map.
 *
 * The hierarchy is carried by stroke *weight*, not by colour: one blue getting
 * heavier as the level broadens reads as a nested hierarchy, where four colours
 * would read as four unrelated things. Only the upazila level is filled — the
 * requirement that its stroke is blue is satisfied by every level being blue.
 */
const BOUNDARY_BLUE = '#2563EB';

function style(entityType: string, fillOpacity: number, strokeWidth: number): AreaStyle {
  return {
    entity_type: entityType,
    configured: false,
    fill_color: BOUNDARY_BLUE,
    fill_opacity: fillOpacity,
    stroke_color: BOUNDARY_BLUE,
    stroke_opacity: 1,
    stroke_width: strokeWidth,
    z_index: 1,
  };
}

export const FALLBACK_AREA_STYLES: Record<BoundaryLevelKey, AreaStyle> = {
  country: style('country', 0, 3),
  division: style('division', 0, 2),
  district: style('district', 0, 1.25),
  upazila: style('upazila', 0.18, 0.75),
};

/**
 * How much of the world outside Bangladesh is hidden.
 *
 * Not fully opaque: the point is that the dashboard is *about* Bangladesh, and
 * keeping the neighbouring coastline and rivers faintly visible is what stops
 * the country reading as an island floating on a flat colour.
 */
export const MASK_PAINT = {
  light: { color: '#0F172A', opacity: 0.55 },
  dark: { color: '#020617', opacity: 0.72 },
} as const;

/**
 * `[west, south, east, north]` — the extent of Bangladesh.
 *
 * A last resort only. The map fits itself to the bbox the country GeoJSON
 * carries, so this is used when that file cannot be read at all, which is also
 * the case where nothing would be drawn to fit to.
 */
export const BANGLADESH_BOUNDS: [number, number, number, number] = [
  88.0, 20.5, 92.7, 26.7,
];

/** Padding, in pixels, left around the country when the map fits to it. */
export const FIT_PADDING = 32;

/** Source and layer identifiers, so nothing addresses a layer by a literal. */
export const IDS = {
  maskSource: 'bgd-mask',
  maskLayer: 'bgd-mask-fill',
  boundarySource: (level: BoundaryLevelKey) => `bgd-${level}`,
  boundaryFill: (level: BoundaryLevelKey) => `bgd-${level}-fill`,
  boundaryLine: (level: BoundaryLevelKey) => `bgd-${level}-line`,
  capitalsSource: 'bgd-capitals',
  capitalsLayer: 'bgd-capitals-symbol',
  linesSource: 'bgd-lines',
  linesLayer: 'bgd-lines-line',
  entitySource: 'business-entities',
  entityCircles: 'business-entities-circle',
  entityIcons: 'business-entities-icon',
  entityLabels: 'business-entities-label',
} as const;
