/**
 * Everything the map is configured with, in one place.
 *
 * The engine is MapLibre GL JS and the basemap is OpenFreeMap. Neither needs an
 * API key, which is the reason for the pair: the previous implementation carried
 * a Google Maps browser key that had to be served to the page and restricted by
 * referrer, and a hand-written Web Mercator canvas renderer as the fallback for
 * deployments without one. One engine that works everywhere replaces both.
 *
 * Administrative geometry is served from `public/geo/`, generated by
 * `scripts/build_map_geojson.py` from the published HDX release. It is a static
 * asset, not an endpoint: boundaries change only when somebody imports a new
 * release, so a request per page load would be work with no answer that differs.
 * Business data still comes from the API, because that is the only thing that
 * knows the caller's permissions.
 */

import type { AreaStyle } from '../../types/api';

/**
 * OpenFreeMap style URLs, one per theme.
 *
 * Both are deliberately muted designs rather than the colourful `liberty` or
 * `bright` styles the same host offers: a business map is read for the data
 * drawn on top of it, and a vivid basemap competes with the very markers and
 * boundaries it exists to support.
 *
 * The backend may override these through `/api/map/config`, so a deployment
 * behind a firewall can point at its own tile server without a rebuild.
 */
export const BASEMAP_STYLES = {
  light: 'https://tiles.openfreemap.org/styles/positron',
  dark: 'https://tiles.openfreemap.org/styles/dark',
} as const;

/** Where `scripts/build_map_geojson.py` writes, relative to the site root. */
const GEO = '/geo';

export const GEO_FILES = {
  country: `${GEO}/bgd_admin0.geojson`,
  division: `${GEO}/bgd_admin1.geojson`,
  district: `${GEO}/bgd_admin2.geojson`,
  upazila: `${GEO}/bgd_admin3.geojson`,
  capitals: `${GEO}/bgd_admincapitals.geojson`,
  points: `${GEO}/bgd_adminpoints.geojson`,
  lines: `${GEO}/bgd_adminlines.geojson`,
  mask: `${GEO}/bgd_mask.geojson`,
} as const;

export type GeoFileKey = keyof typeof GEO_FILES;

/**
 * The four administrative levels, outermost first.
 *
 * `code` is the P-code the published file carries (`BD`, `BD10`, `BD1004`,
 * `BD20030004`) and the same value `dim_country`/`dim_division`/`dim_district`/
 * `dim_upazila` store, which is what lets a locally-drawn polygon be joined to a
 * server-computed metric without a lookup table between them.
 */
export interface BoundaryLevel {
  key: 'country' | 'division' | 'district' | 'upazila';
  file: GeoFileKey;
  labelKey: string;
  /** Below this zoom the level is not drawn: 507 upazilas at zoom 6 is mush. */
  minZoom: number;
  /** On by default? Only the country outline and upazilas are, per level 12. */
  defaultOn: boolean;
}

export const BOUNDARY_LEVELS: readonly BoundaryLevel[] = [
  { key: 'country', file: 'country', labelKey: 'map.levelCountry', minZoom: 0, defaultOn: true },
  { key: 'division', file: 'division', labelKey: 'map.levelDivision', minZoom: 0, defaultOn: true },
  { key: 'district', file: 'district', labelKey: 'map.levelDistrict', minZoom: 6, defaultOn: false },
  { key: 'upazila', file: 'upazila', labelKey: 'map.levelUpazila', minZoom: 7, defaultOn: false },
] as const;

export type BoundaryLevelKey = BoundaryLevel['key'];

/**
 * Appearance if the API has not answered yet.
 *
 * The authority is `map_area_styles` in the database, served through
 * `/api/map/config` — a colour decided in the browser would be a second source
 * of truth, and the marker designer would no longer describe what is drawn.
 * These values are the same ones migrations `0010` and `0017` seed, so the first
 * paint matches the configured one instead of flashing a different map.
 *
 * The hierarchy is carried by stroke *weight* and stroke *value* together, and
 * still by one hue: four unrelated colours would read as four unrelated things,
 * but weight alone was not enough separation on an executive display, where the
 * country outline has to be findable at a glance and the upazila mesh has to
 * recede behind the business data drawn over it. So the blue darkens as the
 * level broadens — country darkest and heaviest, upazila lightest and thinnest.
 * Only the upazila level is filled, and lightly, for the same reason.
 */
const BOUNDARY_BLUE = {
  country: '#1D4ED8',
  division: '#2563EB',
  district: '#60A5FA',
  upazila: '#93C5FD',
} as const;

function style(
  entityType: BoundaryLevelKey,
  fillOpacity: number,
  strokeWidth: number,
): AreaStyle {
  return {
    entity_type: entityType,
    configured: false,
    fill_color: BOUNDARY_BLUE[entityType],
    fill_opacity: fillOpacity,
    stroke_color: BOUNDARY_BLUE[entityType],
    stroke_opacity: 1,
    stroke_width: strokeWidth,
    z_index: 1,
  };
}

export const FALLBACK_AREA_STYLES: Record<BoundaryLevelKey, AreaStyle> = {
  country: style('country', 0, 3),
  division: style('division', 0, 1.8),
  district: style('district', 0, 1),
  upazila: style('upazila', 0.05, 0.5),
};

/**
 * How much of the world outside Bangladesh is hidden.
 *
 * Not fully opaque: the point is that the dashboard is *about* Bangladesh, and
 * keeping the neighbouring coastline and rivers faintly visible is what stops
 * the country reading as an island floating on a flat colour.
 */
export const MASK_PAINT = {
  light: { color: '#1E293B', opacity: 0.32 },
  dark: { color: '#020617', opacity: 0.55 },
} as const;

/**
 * Paint overrides applied to the *basemap's own* layers after it loads.
 *
 * OpenFreeMap positron is the right basemap for an executive display — it is
 * the quietest of the styles the host offers — but two of its choices work
 * against a business map. Water is `rgb(194,200,202)`, a grey barely separable
 * from the `rgb(242,243,240)` land, so the Bay of Bengal and the river network
 * that define Bangladesh's shape read as more land; and the road casings carry
 * as much visual weight as the administrative boundaries drawn on top of them.
 *
 * These are overrides rather than a forked style: the style stays the host's to
 * maintain, and a layer that disappears from a future release is skipped rather
 * than breaking the map (`refineBasemap` checks each id exists). Keyed by the
 * layer ids positron and dark both use, so one table serves both themes.
 *
 * Only `line-opacity`, `fill-color` and `line-color` are touched — never a
 * width, a filter or a layout property, so nothing changes about what the
 * basemap *shows*, only how loudly it says it.
 */
export const BASEMAP_REFINEMENTS: readonly {
  id: string;
  property: 'fill-color' | 'line-color' | 'line-opacity';
  light: string | number;
  dark: string | number;
}[] = [
  // Water, the one thing made *more* prominent: a recognisable blue at a value
  // that still sits behind the data, rather than the near-grey it ships with.
  { id: 'water', property: 'fill-color', light: '#BFD6E8', dark: '#0B1F2E' },
  { id: 'waterway', property: 'line-color', light: '#9DBBD4', dark: '#123243' },

  // Roads: kept, quietened. The casings are the clutter — the white inner lines
  // still describe the network, so the shape of a city survives at lower weight.
  { id: 'highway_major_casing', property: 'line-opacity', light: 0.45, dark: 0.45 },
  { id: 'highway_motorway_casing', property: 'line-opacity', light: 0.45, dark: 0.45 },
  { id: 'highway_minor', property: 'line-opacity', light: 0.5, dark: 0.5 },
  { id: 'highway_path', property: 'line-opacity', light: 0.35, dark: 0.35 },
  { id: 'railway', property: 'line-opacity', light: 0.4, dark: 0.4 },

  // The basemap's own country and state lines, which otherwise compete with the
  // administrative boundaries this application draws from its own GeoJSON.
  { id: 'boundary_2', property: 'line-opacity', light: 0.25, dark: 0.25 },
  { id: 'boundary_3', property: 'line-opacity', light: 0.15, dark: 0.15 },
] as const;

/**
 * `[west, south, east, north]` — the extent of Bangladesh.
 *
 * A last resort only. The map fits itself to the bbox the country GeoJSON
 * carries, so this is used when that file cannot be read at all, which is also
 * the case where nothing would be drawn to fit to.
 */
export const BANGLADESH_BOUNDS: [number, number, number, number] = [
  88.0, 20.5, 92.7, 26.7,
];

/** Padding, in pixels, left around the country when the map fits to it. */
export const FIT_PADDING = 32;

/** Source and layer identifiers, so nothing addresses a layer by a literal. */
export const IDS = {
  maskSource: 'bgd-mask',
  maskLayer: 'bgd-mask-fill',
  boundarySource: (level: BoundaryLevelKey) => `bgd-${level}`,
  boundaryFill: (level: BoundaryLevelKey) => `bgd-${level}-fill`,
  boundaryLine: (level: BoundaryLevelKey) => `bgd-${level}-line`,
  capitalsSource: 'bgd-capitals',
  capitalsLayer: 'bgd-capitals-symbol',
  linesSource: 'bgd-lines',
  linesLayer: 'bgd-lines-line',
  entitySource: 'business-entities',
  entityCircles: 'business-entities-circle',
  entityIcons: 'business-entities-icon',
  entityLabels: 'business-entities-label',
} as const;
