/**
 * Everything the map is configured with, in one place.
 *
 * The engine is MapLibre GL JS and the basemap is OpenFreeMap. Neither needs an
 * API key, which is the reason for the pair: the previous implementation carried
 * a Google Maps browser key that had to be served to the page and restricted by
 * referrer, and a hand-written Web Mercator canvas renderer as the fallback for
 * deployments without one. One engine that works everywhere replaces both.
 *
 * Administrative geometry is served from `public/geo/`, generated by
 * `scripts/build_map_geojson.py` from the published HDX release. It is a static
 * asset, not an endpoint: boundaries change only when somebody imports a new
 * release, so a request per page load would be work with no answer that differs.
 * Business data still comes from the API, because that is the only thing that
 * knows the caller's permissions.
 */

import type { AreaStyle } from '../../types/api';

/**
 * OpenFreeMap style URLs, one per theme.
 *
 * Both are deliberately muted designs rather than the colourful `liberty` or
 * `bright` styles the same host offers: a business map is read for the data
 * drawn on top of it, and a vivid basemap competes with the very markers and
 * boundaries it exists to support.
 *
 * The backend may override these through `/api/map/config`, so a deployment
 * behind a firewall can point at its own tile server without a rebuild.
 */
export const BASEMAP_STYLES = {
  light: 'https://tiles.openfreemap.org/styles/positron',
  dark: 'https://tiles.openfreemap.org/styles/dark',
} as const;

/** Where `scripts/build_map_geojson.py` writes, relative to the site root. */
const GEO = '/geo';

export const GEO_FILES = {
  country: `${GEO}/bgd_admin0.geojson`,
  division: `${GEO}/bgd_admin1.geojson`,
  district: `${GEO}/bgd_admin2.geojson`,
  upazila: `${GEO}/bgd_admin3.geojson`,
  capitals: `${GEO}/bgd_admincapitals.geojson`,
  points: `${GEO}/bgd_adminpoints.geojson`,
  lines: `${GEO}/bgd_adminlines.geojson`,
  mask: `${GEO}/bgd_mask.geojson`,
} as const;

export type GeoFileKey = keyof typeof GEO_FILES;

/**
 * The four administrative levels, outermost first.
 *
 * `code` is the P-code the published file carries (`BD`, `BD10`, `BD1004`,
 * `BD20030004`) and the same value `dim_country`/`dim_division`/`dim_district`/
 * `dim_upazila` store, which is what lets a locally-drawn polygon be joined to a
 * server-computed metric without a lookup table between them.
 */
export interface BoundaryLevel {
  key: 'country' | 'division' | 'district' | 'upazila';
  file: GeoFileKey;
  labelKey: string;
  /** Below this zoom the level is not drawn: 507 upazilas at zoom 6 is mush. */
  minZoom: number;
  /** On by default? Only the country outline and upazilas are, per level 12. */
  defaultOn: boolean;
}

export const BOUNDARY_LEVELS: readonly BoundaryLevel[] = [
  { key: 'country', file: 'country', labelKey: 'map.levelCountry', minZoom: 0, defaultOn: true },
  { key: 'division', file: 'division', labelKey: 'map.levelDivision', minZoom: 0, defaultOn: true },
  { key: 'district', file: 'district', labelKey: 'map.levelDistrict', minZoom: 6, defaultOn: false },
  { key: 'upazila', file: 'upazila', labelKey: 'map.levelUpazila', minZoom: 7, defaultOn: false },
] as const;

export type BoundaryLevelKey = BoundaryLevel['key'];

/**
 * Appearance if the API has not answered yet.
 *
 * The authority is `map_area_styles` in the database, served through
 * `/api/map/config` — a colour decided in the browser would be a second source
 * of truth, and the marker designer would no longer describe what is drawn.
 * These values are the same ones migrations `0010` and `0017` seed, so the first
 * paint matches the configured one instead of flashing a different map.
 *
 * The hierarchy is carried by stroke *weight* and stroke *value* together, and
 * still by one hue: four unrelated colours would read as four unrelated things,
 * but weight alone was not enough separation on an executive display, where the
 * country outline has to be findable at a glance and the upazila mesh has to
 * recede behind the business data drawn over it. So the blue darkens as the
 * level broadens — country darkest and heaviest, upazila lightest and thinnest.
 * Only the upazila level is filled, and lightly, for the same reason.
 */
const BOUNDARY_BLUE = {
  country: '#1D4ED8',
  division: '#2563EB',
  district: '#60A5FA',
  upazila: '#93C5FD',
} as const;

function style(
  entityType: BoundaryLevelKey,
  fillOpacity: number,
  strokeWidth: number,
): AreaStyle {
  return {
    entity_type: entityType,
    configured: false,
    fill_color: BOUNDARY_BLUE[entityType],
    fill_opacity: fillOpacity,
    stroke_color: BOUNDARY_BLUE[entityType],
    stroke_opacity: 1,
    stroke_width: strokeWidth,
    z_index: 1,
  };
}

export const FALLBACK_AREA_STYLES: Record<BoundaryLevelKey, AreaStyle> = {
  country: style('country', 0, 3),
  division: style('division', 0, 1.8),
  district: style('district', 0, 1),
  upazila: style('upazila', 0.05, 0.5),
};

/**
 * How much of the world outside Bangladesh is hidden.
 *
 * Not fully opaque: the point is that the dashboard is *about* Bangladesh, and
 * keeping the neighbouring coastline and rivers faintly visible is what stops
 * the country reading as an island floating on a flat colour.
 */
export const MASK_PAINT = {
  light: { color: '#1E293B', opacity: 0.32 },
  dark: { color: '#020617', opacity: 0.55 },
} as const;

/**
 * Paint overrides applied to the *basemap's own* layers after it loads.
 *
 * OpenFreeMap positron is the right basemap for an executive display — it is
 * the quietest of the styles the host offers — but two of its choices work
 * against a business map. Water is `rgb(194,200,202)`, a grey barely separable
 * from the `rgb(242,243,240)` land, so the Bay of Bengal and the river network
 * that define Bangladesh's shape read as more land; and the road casings carry
 * as much visual weight as the administrative boundaries drawn on top of them.
 *
 * These are overrides rather than a forked style: the style stays the host's to
 * maintain, and a layer that disappears from a future release is skipped rather
 * than breaking the map (`refineBasemap` checks each id exists). Keyed by the
 * layer ids positron and dark both use, so one table serves both themes.
 *
 * Only colour and opacity are touched — never a width, a filter or a layout
 * property, so nothing changes about what the basemap *shows*, only how loudly
 * it says it.
 *
 * The light values are the dashboard's corporate palette: land #F5F7FA, water
 * #DCEAF5, minor roads #D5D9DE, major roads #B8C0CA, labels #64748B. Stated as
 * a flat scale of greys and one blue so that every colour a reader sees on this
 * map that is *not* in that list belongs to the sales data.
 */
export const BASEMAP_REFINEMENTS: readonly {
  id: string;
  property:
    | 'fill-color'
    | 'line-color'
    | 'line-opacity'
    | 'background-color'
    | 'text-color'
    | 'text-halo-color';
  light: string | number;
  dark: string | number;
}[] = [
  // Land. positron ships rgb(242,243,240), a faintly warm grey; the corporate
  // ground is a cool one, so the blues drawn on it read as the same family.
  { id: 'background', property: 'background-color', light: '#F5F7FA', dark: '#0C0C0C' },
  { id: 'landuse_residential', property: 'fill-color', light: '#EDF0F5', dark: '#141414' },
  { id: 'park', property: 'fill-color', light: '#E8EEE9', dark: '#101410' },

  // Water, the one thing made *more* prominent: a recognisable blue at a value
  // that still sits behind the data, rather than the near-grey it ships with.
  { id: 'water', property: 'fill-color', light: '#DCEAF5', dark: '#0B1F2E' },
  { id: 'waterway', property: 'line-color', light: '#BFD6E8', dark: '#123243' },

  // Roads: kept, quietened, and given the two greys the palette names — minor
  // #D5D9DE, major #B8C0CA. The casings carry the weight, so they take the
  // darker of the two and the inner fills stay light.
  { id: 'highway_minor', property: 'line-color', light: '#D5D9DE', dark: '#181818' },
  { id: 'highway_major_casing', property: 'line-color', light: '#B8C0CA', dark: '#3C3C3C' },
  { id: 'highway_motorway_casing', property: 'line-color', light: '#B8C0CA', dark: '#3C3C3C' },
  { id: 'highway_major_casing', property: 'line-opacity', light: 0.45, dark: 0.45 },
  { id: 'highway_motorway_casing', property: 'line-opacity', light: 0.45, dark: 0.45 },
  { id: 'highway_minor', property: 'line-opacity', light: 0.5, dark: 0.5 },
  { id: 'highway_path', property: 'line-opacity', light: 0.35, dark: 0.35 },
  { id: 'railway', property: 'line-opacity', light: 0.4, dark: 0.4 },

  // The basemap's own country and state lines, which otherwise compete with the
  // administrative boundaries this application draws from its own GeoJSON.
  { id: 'boundary_2', property: 'line-opacity', light: 0.25, dark: 0.25 },
  { id: 'boundary_3', property: 'line-opacity', light: 0.15, dark: 0.15 },

  /* Place labels, on one slate. positron greys them from #000 for a village up
     to #333 for a country, which is a hierarchy of *place* — useful on a road
     map, competing noise on a sales map, where the hierarchy that matters is
     the one the boundaries and the data draw. One tone, #64748B, is the same
     slate the dashboard writes its own secondary text in. */
  { id: 'label_country_1', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_country_2', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_country_3', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_state', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_city', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_city_capital', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_town', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_village', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'label_other', property: 'text-color', light: '#64748B', dark: '#94A3B8' },
  { id: 'water_name_point_label', property: 'text-color', light: '#8FA8BF', dark: '#5B7A93' },
  { id: 'water_name_line_label', property: 'text-color', light: '#8FA8BF', dark: '#5B7A93' },
  // Road names are the least of it, and go quieter still.
  { id: 'highway-name-minor', property: 'text-color', light: '#9AA3AD', dark: '#4A4A4A' },
  { id: 'highway-name-major', property: 'text-color', light: '#9AA3AD', dark: '#4A4A4A' },
] as const;

/**
 * `[west, south, east, north]` — the extent of Bangladesh.
 *
 * A last resort only. The map fits itself to the bbox the country GeoJSON
 * carries, so this is used when that file cannot be read at all, which is also
 * the case where nothing would be drawn to fit to.
 */
export const BANGLADESH_BOUNDS: [number, number, number, number] = [
  88.0, 20.5, 92.7, 26.7,
];

/** Padding, in pixels, left around the country when the map fits to it. */
export const FIT_PADDING = 32;

/** Source and layer identifiers, so nothing addresses a layer by a literal. */
export const IDS = {
  maskSource: 'bgd-mask',
  maskLayer: 'bgd-mask-fill',
  boundarySource: (level: BoundaryLevelKey) => `bgd-${level}`,
  boundaryFill: (level: BoundaryLevelKey) => `bgd-${level}-fill`,
  boundaryLine: (level: BoundaryLevelKey) => `bgd-${level}-line`,
  capitalsSource: 'bgd-capitals',
  capitalsLayer: 'bgd-capitals-symbol',
  linesSource: 'bgd-lines',
  linesLayer: 'bgd-lines-line',
  entitySource: 'business-entities',
  entityCircles: 'business-entities-circle',
  entityIcons: 'business-entities-icon',
  entityLabels: 'business-entities-label',
  bubbleSource: 'business-bubbles',
  bubbleCircles: 'business-bubbles-circle',
} as const;

/* -------------------------------------------------------------- map modes */

/**
 * What the map is *about* right now.
 *
 * A mode is a way of reading the same geography, not a different map: every one
 * of them draws the same boundaries over the same basemap and differs only in
 * what carries the meaning — the outline, a choropleth fill, or the markers.
 *
 * `metric` names a key from `/api/map/config`'s `metrics`, which is the server's
 * list and the only source of truth for what can be measured. A mode whose
 * metric the server does not offer is **unavailable**, and is shown that way
 * rather than hidden: the reader should be able to see that Sales Achievement is
 * a thing this dashboard means to show and does not have the data for yet.
 * Nothing here invents a number — an unavailable mode has no fill and no legend.
 */
export type MapModeKey =
  | 'administrative'
  | 'bubble'
  | 'performance'
  | 'density'
  | 'promotion';

/**
 * What a mode draws with, kept separate from what it measures.
 *
 * Three axes, deliberately independent, so a future choropleth is a new
 * `geometry` value rather than a rewrite:
 *
 * * **geometry** - what carries the value. `point` is every mode today: each
 *   region, territory or customer has its own coordinate. `area` is reserved
 *   for a choropleth over administrative polygons and is not yet used, because
 *   this warehouse attributes no metric to an area (see `map/areas.py`).
 * * **metric** - a key from `/api/map/config`'s list, which is the server's
 *   word on what can be measured. Never assumed here.
 * * **encoding** - how the value reaches the eye: size, colour, both, or
 *   `count` for a density surface that measures nothing but presence.
 */
export type MapGeometry = 'point' | 'area';
export type MapEncoding = 'none' | 'size' | 'colour' | 'size+colour' | 'count';

export interface MapMode {
  key: MapModeKey;
  labelKey: string;
  geometry: MapGeometry;
  /** Metric key the mode reads, or null where it measures nothing. */
  metric: string | null;
  encoding: MapEncoding;
  /** Why the mode cannot run, when the data for it does not exist. */
  unavailableKey?: string;
}

/**
 * The modes, in reading order.
 *
 * There is deliberately **no choropleth and no area heat map**. Both would need
 * a metric attributed to administrative polygons, and the warehouse has none:
 * `map/areas.py` returns an empty mapping from `stock_by_area` and
 * `_optional_metrics` alike. An earlier version of this page painted the
 * fallback value those return and so coloured every area identically - a
 * constant dressed as a measurement. Sales are real per *point*, and that is
 * what these modes read.
 */
export const MAP_MODES: readonly MapMode[] = [
  {
    key: 'administrative', labelKey: 'map.modeAdministrative',
    geometry: 'point', metric: null, encoding: 'none',
  },
  {
    key: 'bubble', labelKey: 'map.modeBubble',
    geometry: 'point', metric: 'achievement', encoding: 'size+colour',
  },
  {
    key: 'performance', labelKey: 'map.modePerformance',
    geometry: 'point', metric: 'achievement', encoding: 'size+colour',
  },
  {
    key: 'density', labelKey: 'map.modeDensity',
    geometry: 'point', metric: null, encoding: 'count',
  },
  {
    key: 'promotion', labelKey: 'map.modePromotion',
    geometry: 'point', metric: null, encoding: 'none',
    unavailableKey: 'map.modeNeedsPromotion',
  },
] as const;

export const MODE_BY_KEY: Record<MapModeKey, MapMode> = Object.fromEntries(
  MAP_MODES.map((mode) => [mode.key, mode]),
) as Record<MapModeKey, MapMode>;

/**
 * The sequential ramp, light to dark, for a magnitude with no natural midpoint.
 *
 * Five steps rather than a continuous interpolation: a reader compares an area
 * against a legend, and five swatches can be told apart where a gradient cannot.
 * Light-to-dark of one hue, so the ordering is legible without reading the key —
 * and the same blue family the boundaries use, because this is the same map.
 */
export const SEQUENTIAL_RAMP: readonly string[] = [
  '#EFF6FF', '#BFDBFE', '#7EB3F5', '#3B82F6', '#1D4ED8',
];

/**
 * Achievement bands, in the order a reader thinks about them.
 *
 * Not a gradient: these are *thresholds a business has agreed*, so the breaks
 * are the meaning and must be exact. Red below 50, orange to 70, yellow to 90,
 * green to 100, dark green above — under-performance warm, target-and-above
 * cool, with the boundary at 100 the one that matters most.
 */
export const ACHIEVEMENT_BANDS: readonly { max: number | null; color: string; labelKey: string }[] = [
  { max: 50, color: '#DC2626', labelKey: 'map.band0' },
  { max: 70, color: '#EA580C', labelKey: 'map.band50' },
  { max: 90, color: '#CA8A04', labelKey: 'map.band70' },
  { max: 100, color: '#16A34A', labelKey: 'map.band90' },
  { max: null, color: '#15803D', labelKey: 'map.band100' },
] as const;
